### ISSUE TITLE
Matching multiple file extensions

### ISSUE THREAD

**Issue by solid-maxim** [kt3k/deno_license_checker#11]
Hello. Seems like multiple matching is not working: `"**/*.{js,ts}".` I've tested with different forms of globs. 

The License checker just ignores all the files and quietly passes without any outputs.

**Comment by kt3k** [comment]
Can you create a reproduction repository for this case? `"**/*.{js,ts}"` seems working at least for my case...

**Comment by solid-maxim** [comment]
Can you look at this repo: https://github.com/solid-maxim/test_word_presence/pull/4? Check is passed, but a license text is missing.

**Comment by kt3k** [comment]
Ah, I haven't update the github actions version of this script for a while, and probably that caused the issue. I've just published version 1.0.4 of `kt3k/license_checker`. Please try update your github action to `kt3k/license_checker@v1.0.4`.

**Comment by solid-maxim** [comment]
Now it works. Thanks!
