### ISSUE TITLE
Add option to allow multiple types of licenses

### ISSUE THREAD

**Issue by Pandapip1** [kt3k/deno_license_checker#27]
For one use case, I would like to allow a list of non-copyleft licenses, but leave users the option on which one to pick.

**Comment by kt3k** [comment]
Can you provide the example of license headers of the above case?

**Comment by Pandapip1** [comment]
```js
// SPDX-License-Identifier: Apache-2
```
```js
// SPDX-License-Identifier: MIT
```
```js
// SPDX-License-Identifier: CC0-1.0
```

**Comment by kt3k** [comment]
Why is each file differently licensed? I think a normal project has a single license and all files follow it. I feel your project is out of scope of this tool

**Comment by Pandapip1** [comment]
Fair enough. Do you have a suggestion for another tool that might work better?

**Comment by kt3k** [comment]
I don't think there's a special tool for that case. I would write my own script for it.
