### ISSUE TITLE
Allow Regex in licenses

### ISSUE THREAD

**Issue by Pandapip1** [kt3k/deno_license_checker#28]
For another use case, I need to allow either of the following:

```js
// Code
```

```js
// SPDX-License-Identifier: CC0-1.0

// Code
```

But disallow other licenses, such as:

```js
// SPDX-License-Identifier: MIT

// Code
```

Is it possible to allow regex?

```regex
/(^\/+\ *SPDX-License-Identifier: CC0-1\.0.*$|^[^\/].*$)/gm
```

**Comment by kt3k** [comment]
Writing (and reading) regex in json is painful in my view. So I want to avoid allowing regex in the config.

In the above example, why some file has license header and some are not? Doesn't `ignore` parameter work for that case?

**Comment by Pandapip1** [comment]
`ignore` doesn't work since that takes in a list of files, and the repo in question mostly deals with new files.
